    x(4);
    x(5);
    x(6);
    Derivative(1)(Subscript(q,3))(t);
    -(((Subscript(c,r) + Subscript(c,t))*x(4))/m) + (Subscript(c,t)*x(5))/m + (Subscript(k,t)*(-x(1) + x(2)) + Subscript(k,r)*(-x(1) + Subscript(y,ext)(t)) + Subscript(c,r)*Derivative(1)(Subscript(y,ext))(t))/m;
    (Subscript(c,t)*Subscript(J,oz)*x(4))/(M*(-(M*(Subscript(D,GO)*Subscript(D,GO))) + Subscript(J,oz))) + ((-(M*Subscript(c,Tf)*Subscript(D,FO)*Subscript(D,GO)) + (Subscript(c,t) + Subscript(c,Tf))*Subscript(J,oz))*x(5))/(M*(M*(Subscript(D,GO)*Subscript(D,GO)) - Subscript(J,oz))) + (Subscript(c,Tf)*Subscript(D,FO)*(-(M*Subscript(D,FO)*Subscript(D,GO)) + Subscript(J,oz))*x(6))/(M*(M*(Subscript(D,GO)*Subscript(D,GO)) - Subscript(J,oz))) + (M*(Subscript(D,GO)*Subscript(D,GO))*(-2*g*M + (2*g*M - S*\[Rho]*Subscript(C,L)*((Subscript(u,longit) + Subscript(u,vento))*(Subscript(u,longit) + Subscript(u,vento))))*Subscript(\[Mu],rol)*x(3)) - Subscript(J,oz)*(S*\[Rho]*Subscript(C,L)*((Subscript(u,longit) + Subscript(u,vento))*(Subscript(u,longit) + Subscript(u,vento))) - 2*(Subscript(k,t)*(-x(1) + x(2)) + Subscript(k,Tf)*(x(2) + Subscript(D,FO)*x(3) - Subscript(q,3)(t)))) + M*Subscript(D,GO)*(S*\[Rho]*Subscript(D,PO)*((Subscript(u,longit) + Subscript(u,vento))*(Subscript(u,longit) + Subscript(u,vento)))*(Subscript(C,L) + Subscript(C,D)*x(3)) - 2*Subscript(D,FO)*Subscript(k,Tf)*(x(2) + Subscript(D,FO)*x(3) - Subscript(q,3)(t))))/(2.*M*(M*(Subscript(D,GO)*Subscript(D,GO)) - Subscript(J,oz))) + (Subscript(c,Tf)*(M*Subscript(D,FO)*Subscript(D,GO) - Subscript(J,oz))*Derivative(1)(Subscript(q,3))(t))/(M*(M*(Subscript(D,GO)*Subscript(D,GO)) - Subscript(J,oz)));
    (Subscript(c,t)*Subscript(D,GO)*x(4))/(M*(Subscript(D,GO)*Subscript(D,GO)) - Subscript(J,oz)) + ((Subscript(c,Tf)*Subscript(D,FO) - (Subscript(c,t) + Subscript(c,Tf))*Subscript(D,GO))*x(5))/(M*(Subscript(D,GO)*Subscript(D,GO)) - Subscript(J,oz)) + (Subscript(c,Tf)*Subscript(D,FO)*(Subscript(D,FO) - Subscript(D,GO))*x(6))/(M*(Subscript(D,GO)*Subscript(D,GO)) - Subscript(J,oz)) + (-(S*\[Rho]*Subscript(D,PO)*((Subscript(u,longit) + Subscript(u,vento))*(Subscript(u,longit) + Subscript(u,vento)))*(Subscript(C,L) + Subscript(C,D)*x(3))) + Subscript(D,GO)*(S*\[Rho]*Subscript(C,L)*((Subscript(u,longit) + Subscript(u,vento))*(Subscript(u,longit) + Subscript(u,vento)))*(1 + Subscript(\[Mu],rol)*x(3)) - 2*(-(g*M) + Subscript(k,t)*(-x(1) + x(2)) + Subscript(D,FO)*Subscript(k,Tf)*x(3) + g*M*Subscript(\[Mu],rol)*x(3) + Subscript(k,Tf)*(x(2) - Subscript(q,3)(t)))) + 2*Subscript(D,FO)*Subscript(k,Tf)*(x(2) + Subscript(D,FO)*x(3) - Subscript(q,3)(t)))/(2*M*(Subscript(D,GO)*Subscript(D,GO)) - 2*Subscript(J,oz)) + (Subscript(c,Tf)*(Subscript(D,FO) - Subscript(D,GO))*Derivative(1)(Subscript(q,3))(t))/(-(M*(Subscript(D,GO)*Subscript(D,GO))) + Subscript(J,oz));
    (Subscript(c,Tf)*x(5))/Subscript(m,f) + (Subscript(c,Tf)*Subscript(D,FO)*x(6))/Subscript(m,f) - ((Subscript(c,rf) + Subscript(c,Tf))*Derivative(1)(Subscript(q,3))(t))/Subscript(m,f) + (Subscript(k,Tf)*(x(2) + Subscript(D,FO)*x(3) - Subscript(q,3)(t)) + Subscript(k,rf)*(-Subscript(q,3)(t) + Subscript(y,ext)(t)) + Subscript(c,rf)*Derivative(1)(Subscript(y,ext))(t))/Subscript(m,f);

