yL_0(5);
yL_0(6);
yL_0(7);
yL_0(8);
-(((c_r + c_t)*yL_0(5))/m) + (c_t*yL_0(6))/m + (k_t*(-yL_0(1) + yL_0(2)) + k_r*(-yL_0(1) + y_ext) + c_r*yponto_ext)/m;
(c_t*J_oz*yL_0(5))/(M*(-(M*(cos(phi)*cos(phi))*(D_go*D_go)) + J_oz)) + ((-(M*(cos(phi)*cos(phi))*c_tf*D_fo*D_go) + (c_t + c_tf)*J_oz)*yL_0(6))/(M*(M*(cos(phi)*cos(phi))*(D_go*D_go) - J_oz)) + (cos(phi)*c_tf*D_fo*(-(M*(cos(phi)*cos(phi))*D_fo*D_go) + J_oz)*yL_0(7))/(M*(M*(cos(phi)*cos(phi))*(D_go*D_go) - J_oz)) - (M*cos(phi)*(D_go*D_go)*(-((2*g*M - S*rho*C_L*((yL_0(10) + u_v)*(yL_0(10) + u_v)))*u_rol*(sin(phi) + cos(phi)*yL_0(3))) + 2*g*M*(cos(phi) - sin(phi)*yL_0(3))) + M*cos(phi)*D_go*(D_fo*D_fo*k_tf*(sin(2*phi) + 2*cos(2*phi)*yL_0(3)) - S*rho*D_po*((yL_0(10) + u_v)*(yL_0(10) + u_v))*(cos(phi)*(C_L + C_D*yL_0(3)) + sin(phi)*(C_D - C_L*yL_0(3))) + 2*cos(phi)*D_fo*k_tf*(yL_0(2) - yL_0(4))) + J_oz*(S*rho*C_L*((yL_0(10) + u_v)*(yL_0(10) + u_v)) + 2*k_t*(yL_0(1) - yL_0(2)) - 2*k_tf*(yL_0(2) + D_fo*(sin(phi) + cos(phi)*yL_0(3)) - yL_0(4))))/(2.*M*(M*(cos(phi)*cos(phi))*(D_go*D_go) - J_oz)) + (c_tf*(M*(cos(phi)*cos(phi))*D_fo*D_go - J_oz)*yL_0(8))/(M*(M*(cos(phi)*cos(phi))*(D_go*D_go) - J_oz));
(sec(phi)*c_t*D_go*yL_0(5))/(M*(D_go*D_go) - sec(phi)*sec(phi)*J_oz) + (sec(phi)*(-(c_tf*D_fo) + (c_t + c_tf)*D_go)*yL_0(6))/(-(M*(D_go*D_go)) + sec(phi)*sec(phi)*J_oz) + (c_tf*D_fo*(D_fo - D_go)*yL_0(7))/(M*(D_go*D_go) - sec(phi)*sec(phi)*J_oz) - (sec(phi)*(-(sec(phi)*(D_fo*D_fo)*k_tf*(sin(2*phi) + 2*cos(2*phi)*yL_0(3))) + S*rho*D_po*((yL_0(10) + u_v)*(yL_0(10) + u_v))*(C_D*(tan(phi) + yL_0(3)) + C_L*(1 - tan(phi)*yL_0(3))) + D_go*(2*D_fo*k_tf*(sin(phi) + cos(phi)*yL_0(3)) - S*rho*C_L*((yL_0(10) + u_v)*(yL_0(10) + u_v))*(1 + u_rol*(tan(phi) + yL_0(3))) + 2*(-(g*M) + k_t*(-yL_0(1) + yL_0(2)) + g*M*(tan(phi)*yL_0(3) + u_rol*(tan(phi) + yL_0(3))) + k_tf*(yL_0(2) - yL_0(4)))) + 2*D_fo*k_tf*(-yL_0(2) + yL_0(4))))/(2*M*(D_go*D_go) - 2*(sec(phi)*sec(phi))*J_oz) + (sec(phi)*c_tf*(D_fo - D_go)*yL_0(8))/(-(M*(D_go*D_go)) + sec(phi)*sec(phi)*J_oz);
(c_tf*yL_0(6))/m_f + (cos(phi)*c_tf*D_fo*yL_0(7))/m_f - ((c_rf + c_tf)*yL_0(8))/m_f + (k_tf*(yL_0(2) + D_fo*(sin(phi) + cos(phi)*yL_0(3)) - yL_0(4)) + k_rf*(-yL_0(4) + y_ext) + c_rf*yponto_ext)/m_f;

